
FROM eclipse-temurin:11-jdk-alpine as build
WORKDIR /workspace/app

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src
RUN chmod +x mvnw
RUN ./mvnw install -DskipTests
RUN mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)

FROM eclipse-temurin:11-jre-alpine
LABEL maintainer="fcaudillo@fcaudilloperez1971@gmail.com"
VOLUME /tmp
ARG DEPENDENCY=/workspace/app/target/dependency
COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build ${DEPENDENCY}/BOOT-INF/classes /app

ENTRYPOINT ["java","-Duser.timezone=America/Mexico_City", "-Djava.security.egd=file:/dev/./urandom", "-cp","app:app/lib/*", "com.puntoventa.gateway.ApiGatewayApplication"]