apiVersion: v1
kind: Service
metadata:
  name: nutenta-magento-gateway-service
  labels:
    app.kubernetes.io/name: nutentadev
    app.kubernetes.io/instance: magento-gateway
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: client
  selector:
    app.kubernetes.io/name: nutentadev
    app.kubernetes.io/instance: magento-gateway
---
# Source: nutentadev/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento-gateway
  labels:
    app.kubernetes.io/name: nutentadev
    app.kubernetes.io/instance: magento-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nutentadev
      app.kubernetes.io/instance: magento-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nutentadev
        app.kubernetes.io/instance: magento-gateway
    spec:
      imagePullSecrets:
        - name: rsecret
      containers:
        - name: nutentadev
          securityContext:
            {}
          image: nutentadev.azurecr.io/magento-gateway:1.0.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi